name: Deploy to Sakura VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Setup SSH key
        run: |
          rsync -e "ssh -i ~/.ssh/id_rsa_github" -avz --delete dist/ ubuntu@153.126.164.246:/var/www/spa.codeshift-lab.com/html/

      - name: Deploy via rsync
        run: |
          rsync -avz --delete dist/ ubuntu@153.126.164.246:/var/www/spa.codeshift-lab.com/html/
